export default {
    path: '/manager',
    component: () => import('../../views/Manager/Manager.vue'),
    children:[
        {
            name:'userlist',
            path:'userlist',
            component:()=>import('../../views/Manager/userList.vue'),
            meta:{ requiresAuth: true }
        },
        {
            name:'rolelist',
            path:'rolelist',
            component:()=>import('../..//views/Manager/roleList.vue')
        },
        {
            name:'permission',
            path:'permission',
            component:()=>import('../..//views/Manager/permission.vue')
        },
        {
            name:'newsmanage',
            path:'newsmanage',
            component:()=>import('../..//views/Manager/newsManage.vue'),
        },
        {
            name:'addnews',
            path:'addnews',
            component:()=>import('../../views/Manager/addNews.vue')
        },
        {
            name:'notise',
            path:'notise',
            component:()=>import('../../views/Manager/notice.vue')
        },
        {
            name:'sincere',
            path:'sincere',
            component:()=>import('../../views/Manager/Sincere.vue')
        },
        {
            name:'company',
            path:'company',
            component:()=>import('../../views/Manager/Company.vue')
        },
        {
            name:'more',
            path:'more',
            component:()=>import('../../views/Manager/more/More.vue')
        }
    ]
  } 